add program that allows you to search for mizar's theorem using lsi
mimosa-project/emsearch pull request #1
Opened 2020-12-03 04:43 UTC by atososon

lsiを使ったmizarの定理検索の実装

2020-12-03 05:16 UTC, aabaa requested changes
abs/mizファイル等については，GitHubとは別管理としたほうが良いかと思います．

2020-12-06 03:07 UTC, atososon commented
absファイル等をGithubとは別管理にしました

2020-12-10 08:41 UTC, aabaa requested changes

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +DATA_DIR = '/mnt/c/emparser/build/lib.linux-x86_64-3.6/emparser/data' # 適宜変更
相対パスに

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +
```python
ABS_DIR = ...
```

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +files_file.sort()
```python
files = sorted(glob.glob('*.abs'))
```

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +        variable_check.append(re.sub("[\n]","",l))
判定方法を変える
```python
def is_variable(word):
```

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +variable_type = 0
```python
from collections import defaultdict
variable2appearance = defaultdict(int)
# for example:  variable2appearance = {'a': 2, 'b': 3, 'c': 4}
```

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +    with open("dictionary_abs.txt", "a") as file_dictionary_abs:
dictionary_abs.txtを作成する関数を作る．
```python
def create_abs_dictionary(path):
```
txtファイルの仕様を書く
例) 
(definition or theorem)  (行数) ...  
definition 51 ABCMIZ_0 ABCMIZ_0:def 1 let T be RelStr; attr T is Noetherian means the InternalRel of T is co-well_founded;
theorem 127 ABCMIZ_0 3
  for A1,A2 being AdjectiveStr st the AdjectiveStr of A1 = the
AdjectiveStr of A2 for a1 being adjective of A1, a2 being adjective of A2 st a1
  = a2 holds non-a1 = non-a2;

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +for number_files_file in range(len(files_file)):
for file in files:

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +        with open("./abstr/"+files_file[number_files_file], "r") as name_file:
```python
  with open("./abstr/"+filename, "r") as f:
    lines = f.readlines()
    for line_no, line in enumerate(lines):
       line = line.strip()
```

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +                read_name_file_split = read_name_file.split()
```python
words = line.split()
for word_no, word in words:
  ...

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +            value_definition = []
```python
   is_definition_block # definition_flag = 0
   is_theorem  #  theorem_flag = 0
   #        count_line = 0
   is_definition  #       count_definition = 0
   definition_line_no #        definition_count_line = 0
   theorem_line_no #         theorem_count_line = 0
   is_comment #         theorem_count_comment = 0
   common_definition_statement #         common_definition = []
   indivisual_definition_statement #         value_definition = []
```

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +                            for i in range(1,len(value_definition)):
writeを何度も使わず，先に1行の文字列を作成する
フォーマット済み文字列リテラルを使う

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +with open("parsed_abs.txt", "w") as file_parsed_abs:
parserd_abs.txtの仕様を書く
名前は document_vectors.txtなど
abs_dictionary.txtからdocument_vectors.txtを生成する関数を作る

2020-12-10 08:41 UTC, aabaa commented on parse_abs.py
> +                    tokenized_lines_split = tokenized_lines[i].split(" ")
tokenized_lines_split -> tokens

2020-12-10 08:41 UTC, aabaa commented on search.py
> +    input_doc = [i for i in input_doc if i != ""]
i -> s

2020-12-10 08:41 UTC, aabaa commented on search.py
> +    for idx in sims[:count_top:]:
sims[:count_top:] -> sims[:count_top]

2020-12-10 08:41 UTC, aabaa commented on svd.py
> +
関数化する

2020-12-23 11:26 UTC, atososon commented
pull requestの直しを行いました

2020-12-24 06:36 UTC, aabaa requested changes

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +
```python
RESERVED_WORDS = ('', ....)
```

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +    with open ("abs_dictionary.txt", "w") as file_abs_dictionary:
file_abs_dictionary -> abs_dictionary_file

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +    files = sorted(glob.glob("*.abs"))
files -> abs_files

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +    os.chdir(cwd)
```python
cwd = os.getcwd()
try:
    path = "./abstr"
    os.chdir(path)
finally:
  os.chdir(cwd)
```

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +            with open("./abstr/"+file, "r") as f:
path.joinを使う

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +                is_definition = 0 # definitionのラベル内かどうか
True/Falseに

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +
```python
item = {
  title: "definition",
  line_no: 51
  filename: 
  label: 
  text:
} 
```

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +
ファイル書き込みはここで行う

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +                                    indivisual_definition_statement.append(common_definition_statement.pop())
セミコロンがないならばpopを繰り返す，に変更

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +                            elif line[-1] == ";" and is_definition == 1:
line[-1] == ";"  --> ";" in line に変更

2020-12-24 06:36 UTC, aabaa commented on parse_abs.py
> +def processing_variables_with_emparser(line):
引数にlexerを加えて，lexerの初期化処理は外でやる

2021-03-02 14:24 UTC, atososon commented
pull requestの直しと不具合の修正を行いました

2021-03-04 07:58 UTC, aabaa commented on parse_abs.py
RESERVED_WORDSにin演算子を使うと線形検索になってしまうので，setで括る

2021-03-04 07:58 UTC, aabaa commented on parse_abs.py
> +    if word in RESERVED_WORDS or word.isdecimal() or "__" in word and "_" in word.replace("__", ""):
"__" in word and "_" in word.replace("__", "")
の意味が分かるようにis_symbol()という関数にする．
symbolの区別の仕方は先頭が__であるようなトークン．

2021-03-04 07:58 UTC, aabaa commented on parse_abs.py
ここから関数にする

2021-03-04 07:58 UTC, aabaa commented on parse_abs.py
> +def processing_variables_with_emparser(line, lexer):
名前を replace_variable_name_to_underscore とか

2021-03-04 07:58 UTC, aabaa commented on parse_abs.py
lines = ("begin\n " + " ".join(line)).split(" ")
    lines = lexer.remove_comment(lines)
    tokenized_lines, position_map = lexer.lex(lines)

2021-03-04 07:58 UTC, aabaa commented on parse_abs.py
for i, token in enumerate(tokenized_lines):
        if is_variable(token): # 変数の場合
            variable2appearance[token] += 1
            tokenized_lines[i] = "___"
        tokenized_lines[i] = re.sub("__[^_]+_", "", tokenized_lines[i])

2021-03-04 08:16 UTC, aabaa requested changes

2021-03-04 08:16 UTC, aabaa commented on parse_abs.py
> +
listでin演算子を使うと線形検索になるのでsetにする

2021-03-04 08:16 UTC, aabaa commented on parse_abs.py
> +    tokenized_lines, position_map = lexer.lex(text_proper_lines)
lines = ("begin\n " + " ".join(line)).split(" ")
lines = lexer.remove_comment(lines)
tokenized_lines, position_map = lexer.lex(lines)

2021-03-04 08:16 UTC, aabaa commented on parse_abs.py
> +        tokenized_lines[i] = re.sub("__[^_]+_", "", tokenized_lines[i])
for i, token in enumerate(tokenized_lines):
    if is_variable(token): # 変数の場合
        variable2appearance[token] += 1
        tokenized_lines[i] = "___"
    tokenized_lines[i] = re.sub("__[^_]+_", "", tokenized_lines[i])

2021-03-04 08:16 UTC, aabaa commented on parse_abs.py
> +                line = line.replace(";", "")
消している理由をコメントする

2021-03-04 08:16 UTC, aabaa commented on parse_abs.py
> +        tell_append = tell.append
この高速化は意味がない

2021-03-04 08:16 UTC, aabaa commented on parse_abs.py
> +        tell = []
tell -> byte_indices

2021-03-04 08:16 UTC, aabaa commented on parse_abs.py
> +def save_abs_dictionary_by_byte():
def save_byte_index_of_lines(input, output):

2021-03-22 04:35 UTC, aabaa requested changes

2021-03-22 04:35 UTC, aabaa commented on parse_abs.py
> +def replace_variable_name_to_underscore(line, lexer):
rename_variable_and_symbol

2021-03-22 07:23 UTC, merged